# Generated by Django 5.0.2 on 2024-02-18 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(max_length=150, null=True)),
                ('headshot', models.ImageField(null=True, upload_to='img/headshots/')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('gender', models.CharField(choices=[('M', 'Cis Gender Male'), ('F', 'Cis Gender Female'), ('N', 'NonBinary'), ('NA', 'Prefer Not To Say')])),
                ('date_of_birth', models.DateField()),
                ('show_horoscope', models.BooleanField(default=True)),
                ('instagram_link', models.URLField(null=True)),
                ('facebook_link', models.URLField(null=True)),
                ('snapchat_link', models.URLField(null=True)),
                ('inviteurl', models.URLField()),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
