# Generated by Django 5.0.2 on 2024-02-07 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_established', models.DateTimeField()),
                ('closeness', models.CharField(choices=[('friend', 'Friend'), ('closefriend', 'Close Friend'), ('bestfriend', 'Best Friend')], max_length=20)),
                ('nicknametoparent', models.CharField(max_length=64, null=True)),
                ('nicknametochild', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('bio', models.TextField(max_length=150)),
                ('headshot', models.ImageField(upload_to='headshots/')),
                ('created_time', models.DateTimeField()),
                ('date_of_birth', models.DateField()),
                ('show_horoscope', models.BooleanField(default=True)),
                ('instagram_link', models.URLField(null=True)),
                ('facebook_link', models.URLField(null=True)),
                ('snapchat_link', models.URLField(null=True)),
                ('inviteurl', models.URLField()),
                ('password', models.CharField(max_length=128)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friend_web.gendertype')),
            ],
        ),
        migrations.CreateModel(
            name='Inviterchannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friend_web.connection')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friend_web.user')),
            ],
        ),
        migrations.CreateModel(
            name='Inviteechannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friend_web.connection')),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friend_web.user')),
            ],
        ),
        migrations.AddField(
            model_name='connection',
            name='invitee',
            field=models.ManyToManyField(related_name='invitee_connections', through='friend_web.Inviteechannel', to='friend_web.user'),
        ),
        migrations.AddField(
            model_name='connection',
            name='inviter',
            field=models.ManyToManyField(related_name='inviter_connections', through='friend_web.Inviterchannel', to='friend_web.user'),
        ),
        migrations.AddField(
            model_name='connection',
            name='usedurl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friend_web.user'),
        ),
    ]
