# Generated by Django 5.0.2 on 2024-02-15 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='gender',
            field=models.CharField(choices=[('M', 'Cis Gender Male'), ('F', 'Cis Gender Female'), ('N', 'NonBinary'), ('NA', 'Prefer Not To Say')], default='M'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='GenderType',
        ),
    ]
