# Generated by Django 5.0.2 on 2024-02-18 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_established', models.DateTimeField()),
                ('closeness', models.CharField(choices=[('friend', 'Friend'), ('closefriend', 'Close Friend'), ('bestfriend', 'Best Friend')], max_length=20)),
                ('nicknamechildtoparent', models.CharField(max_length=64, null=True)),
                ('nicknameparenttochild', models.CharField(max_length=64, null=True)),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitee_connections', to='friend_web.userdata')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inviter_connections', to='friend_web.userdata')),
            ],
        ),
        migrations.CreateModel(
            name='Inviteechannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friend_web.connection')),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friend_web.userdata')),
            ],
        ),
        migrations.CreateModel(
            name='Inviterchannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friend_web.connection')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friend_web.userdata')),
            ],
        ),
    ]
