# Generated by Django 5.0.2 on 2024-02-07 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='facebook_link',
            field=models.URLField(blank=True, default='https://www.facebook.com/tuntundragon/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='instagram_link',
            field=models.URLField(blank=True, default='https://www.instagram.com/p/CxPC67MS7nx/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='inviteurl',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='snapchat_link',
            field=models.URLField(blank=True, default='snapchat.com/add/u1'),
            preserve_default=False,
        ),
    ]
