# Generated by Django 5.0.2 on 2024-02-08 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend_web', '0002_alter_user_facebook_link_alter_user_instagram_link_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(max_length=150)),
                ('headshot', models.ImageField(upload_to='img/headshots/')),
                ('created_time', models.DateTimeField()),
                ('date_of_birth', models.DateField()),
                ('show_horoscope', models.BooleanField(default=True)),
                ('instagram_link', models.URLField(blank=True)),
                ('facebook_link', models.URLField(blank=True)),
                ('snapchat_link', models.URLField(blank=True)),
                ('inviteurl', models.URLField(blank=True)),
                ('password', models.CharField(max_length=128)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friend_web.gendertype')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='connection',
            name='invitee',
            field=models.ManyToManyField(related_name='invitee_connections', through='friend_web.Inviteechannel', to='friend_web.userdata'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='inviter',
            field=models.ManyToManyField(related_name='inviter_connections', through='friend_web.Inviterchannel', to='friend_web.userdata'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='usedurl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friend_web.userdata'),
        ),
        migrations.AlterField(
            model_name='inviteechannel',
            name='invitee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friend_web.userdata'),
        ),
        migrations.AlterField(
            model_name='inviterchannel',
            name='inviter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friend_web.userdata'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
