# Generated by Django 5.0.2 on 2024-02-19 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend_web', '0002_connection_inviteechannel_inviterchannel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inviterchannel',
            name='connection',
        ),
        migrations.RemoveField(
            model_name='inviterchannel',
            name='inviter',
        ),
        migrations.AlterField(
            model_name='userdata',
            name='headshot',
            field=models.ImageField(null=True, upload_to='static/img/headshots/'),
        ),
        migrations.DeleteModel(
            name='Inviteechannel',
        ),
        migrations.DeleteModel(
            name='Inviterchannel',
        ),
    ]
