# Generated by Django 5.0.2 on 2024-02-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend_web', '0003_alter_userdata_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='bio',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='headshot',
            field=models.ImageField(null=True, upload_to='img/headshots/'),
        ),
    ]
