# Generated by Django 5.0.2 on 2024-02-11 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friend_web', '0004_alter_userdata_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='password',
        ),
    ]
