# Generated by Django 5.0.2 on 2024-02-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend_web', '0004_alter_userdata_bio_alter_userdata_headshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='facebook_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='instagram_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='inviteurl',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='snapchat_link',
            field=models.URLField(null=True),
        ),
    ]
