# Generated by Django 5.0.2 on 2024-02-22 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend_web', '0004_remove_userdata_id_alter_userdata_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='date_established',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
