# Generated by Django 5.0.2 on 2024-03-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend_web', '0005_alter_connection_date_established'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='activated',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
