# Generated by Django 5.0.2 on 2024-03-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend_web', '0006_connection_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='activated',
            field=models.BooleanField(default=True),
        ),
    ]
