# Generated by Django 5.0.2 on 2024-02-11 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friend_web', '0006_remove_connection_usedurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='nicknametochild',
            new_name='nicknamechildtoparent',
        ),
        migrations.RenameField(
            model_name='connection',
            old_name='nicknametoparent',
            new_name='nicknameparenttochild',
        ),
    ]
