# Generated by Django 5.0.2 on 2024-03-15 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend_web', '0008_alter_connection_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='headshot',
            field=models.ImageField(default='default.png', null=True, upload_to='static/img/headshots/'),
        ),
    ]
