# Generated by Django 5.0.2 on 2024-03-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend_web', '0009_alter_userdata_headshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='gender',
            field=models.CharField(choices=[('M', 'Cis Gender Male'), ('F', 'Cis Gender Female'), ('N', 'Non Binary'), ('NA', 'Prefer Not To Say')]),
        ),
    ]
