# Generated by Django 5.0.2 on 2024-03-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend_web', '0010_connection_updated_time_userdata_updated_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='bio',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='facebook_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='headshot',
            field=models.ImageField(default='static/img/headshots/default.png', null=True, upload_to='static/img/headshots/'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='instagram_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='snapchat_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
